services:
  hbk-reader:
    image: ghcr.io/alkoleft/hbk-viewer:0.4.1
    ports:
      - "8080:8080"
    volumes:
      # Монтируем каталог с HBK файлами
      # Замените /path/to/your/hbk/files на реальный путь к вашим HBK файлам
      - /opt/1cv8/x86_64/8.5.1.189/:/data/hbk:ro
    # environment:
      # Можно переопределить путь к каталогу через переменную окружения
      # HBK_FILES_DIRECTORY: /data/hbk
      # Для отладочного логирования раскомментируйте следующую строку
      # JAVA_OPTS: -Dlogging.level.root=DEBUG
    restart: unless-stopped
