spring:
  application:
    name: hbk-reader
  cache:
    type: simple
  main:
    banner-mode: off

# Настройки HBK файлов для REST API
application:
  hbk-files-directory: ${HBK_FILES_DIRECTORY}

# Настройки логирования
logging:
  level:
    root: INFO
