spring:
  application:
    name: hbk-reader
  cache:
    type: simple
  main:
    banner-mode: off
  jackson:
    default-property-inclusion: NON_NULL

# Настройки HBK файлов для REST API
application:
  hbk-files-directory: ${HBK_FILES_DIRECTORY}

# Настройки логирования
logging:
  level:
    root: INFO
